image: us-west2-docker.pkg.dev/bhojpur/platform/core-dev/dev/dev-environment:cw-bump-gorpa.29
workspaceLocation: bhojpur/bhojpur.code-workspace
checkoutLocation: bhojpur
ports:
  - port: 1337
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
  - port: 3001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  - port: 4000
    onOpen: ignore
  - port: 9229
    onOpen: ignore
# Go proxy
  - port: 9999
    onOpen: ignore
  - port: 13001
    onOpen: ignore
# Piro
  - port: 7777
    onOpen: ignore
# Dev Theia
  - port: 13444
tasks:
  - name: Java
    init: |
      gorpa exec --package components/supervisor-api/java:lib --package components/bhojpur-protocol/java:lib -- ./gradlew build
      gorpa exec --package components/ide/jetbrains/backend-plugin:plugin -- ./gradlew buildPlugin
  - name: TypeScript
    before: scripts/branch-namespace.sh
    init: yarn --network-timeout 100000 && yarn build
  - name: Go
    init: gorpa exec --filter-type go -v -- go mod verify
    openMode: split-right
vscode:
  extensions:
    - bajdzis.vscode-database
    - bradlc.vscode-tailwindcss
    - EditorConfig.EditorConfig
    - golang.go
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - stkb.rewrap
    - zxh404.vscode-proto3
    - matthewpi.caddyfile-support
    - heptio.jsonnet
    - timonwong.shellcheck
    - vscjava.vscode-java-pack
    - fwcd.kotlin