packages:
  - name: lib
    type: generic
    srcs:
      - "**/*.java"
      - "build.gradle"
      - "gradle.properties"
      - "gradle/wrapper/*"
      - "gradlew"
      - "settings.gradle"
    env:
      - JAVA_HOME=/home/bhojpur/.sdkman/candidates/java/current
    config:
      commands:
        - ["./gradlew", "build"]
