version: '3'
services:

  gitpod:
    image: gcr.io/bhojpur/self-hosted/bhojpur-k3s:${VERSION:-latest}
    privileged: true
    volumes:
      - ./values:/values
      - ./certs:/certs
    ports:
      - 443:443
      - 80:80
    environment:
      - DOMAIN=${DOMAIN}
