name: Changelog

on:
  schedule:
    - cron: "0 0 * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    container: us-west2-docker.pkg.dev/bhojpur/platform/changelog:0.0.34

    steps:
      - uses: actions/checkout@v2
      - run: |
          export PR_BRANCH=$(date '+rq/changelog_%Y%m%d%H%M')
          git checkout -b $PR_BRANCH
          /app/changelog update -t $TOKEN -o bhojpur -r platform -b $GITHUB_REF
          if [[ $(git status --porcelain) ]]; then
            git config --global user.name $GITHUB_USER
            git config --global user.email $GITHUB_EMAIL
            git add CHANGELOG.md
            git commit -m "[changelog] updated changelog"
            git push origin $PR_BRANCH
            /app/changelog pr -t $TOKEN -o bhojpur -r platform -b $GITHUB_REF -H $PR_BRANCH
          fi
        env:
          GITHUB_USER: shashi-rai
          GITHUB_EMAIL: shashi.rai@bhojpur-consulting.org
          TOKEN: ${{ secrets.ROBOQUAT_AUTOMATIC_CHANGELOG }}
        shell: bash
